name: Scheduled Update

on:
  schedule:
    - cron: "0 3 * * *"  # Run at 3 AM every day
  push:
    paths-ignore:
      - "**.md"
      - "**.yaml"
  pull_request:
  workflow_dispatch:

jobs:
  check-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check for PokeMMO updates
        id: check
        run: |
          mkdir -p /tmp/pokemmo
          wget -q https://pokemmo.com/download_file/1/ -O /tmp/pokemmo/PokeMMO-Client.zip
          unzip -qq /tmp/pokemmo/PokeMMO-Client.zip -d /tmp/pokemmo
          EXT_RELEASE=$(cat /tmp/pokemmo/revision.txt)
          if [ -z "${EXT_RELEASE}" ]; then
            echo "Failed to get PokeMMO version"
            exit 1
          fi
          echo "version=${EXT_RELEASE}" >> "$GITHUB_OUTPUT"
          echo "Found PokeMMO version: ${EXT_RELEASE}"

      - name: Log into Registry
        if: success()
        uses: docker/login-action@v3
        with:
          registry: forge.dualriver.com
          username: cat
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set up Docker Buildx
        if: success()
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        if: success()
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            forge.dualriver.com/cat/pokemmo-docker:${{ steps.check.outputs.version }}
            forge.dualriver.com/cat/pokemmo-docker:latest
          labels: |
            maintainer=cat
            org.opencontainers.image.version=${{ steps.check.outputs.version }}
