name: Test Docker Image

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: ghcr.io/${{ github.repository_owner_id }}/${{ github.event.repository.name }}-test:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test image
        run: |
          # Set up X11 for testing
          export DISPLAY=:99
          sudo Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          sleep 3

          # Run the container
          docker run -d --name pokemmo \
            -e DISPLAY=:99 \
            -v /tmp/.X11-unix:/tmp/.X11-unix \
            ghcr.io/${{ github.repository_owner_id }}/${{ github.event.repository.name }}-test:latest

          # Wait for container to start
          sleep 10

          # Check if container is running
          docker ps | grep pokemmo

          # Check if Java process is running
          docker exec pokemmo ps aux | grep java

          # Check if ROMs were downloaded
          docker exec pokemmo ls -l /pokemmo/roms/

          # Check logs for any errors
          docker logs pokemmo 